on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: revdeps

jobs:
  revdeps:
    runs-on: macOS-latest
    name: ${{ matrix.config.repository }}@${{ matrix.config.ref }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {repository: paleolimbot/geovctrs, ref: master}
          - {repository: r-spatial/s2, ref: master}

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'wk'
      - uses: actions/checkout@v2
        with:
          repository: ${{ matrix.config.repository }}
          ref: ${{ matrix.config.ref }}
          path: 'pkg'
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "pkgbuild"))
          remotes::install_deps("wk")
          remotes::install_deps("pkg", dependencies = TRUE)
        shell: Rscript {0}

      - name: Build and install wk
        run: |
          Rscript -e 'pkgbuild::build("wk", dest_path = "wk_built")'
          R CMD install wk_built

      - name: Check
        run: rcmdcheck::rcmdcheck("pkg", args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}
